server:
  port: 8080

spring:
  application:
    name: FlightSearch
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/petour
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    enabled: true
    hibernate:
      ddl-auto: validate
#      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
